### ISSUE TITLE
build error: consider giving `accuracy` a type

### ISSUE THREAD

**Issue by treasersimplifies** [substrate-developer-hub/substrate-node-template#123]
Happy New Year 2021!
On the first day of 2021, when I build node-template, I encountered following errors:

it looks the same as #108 , **but even if I follow the solution in #108 **, I still got the above error.....

```shell
$ rustup install nightly-2020-10-05
info: syncing channel updates for 'nightly-2020-10-05-x86_64-apple-darwin'

  nightly-2020-10-05-x86_64-apple-darwin unchanged - rustc 1.49.0-nightly (beb5ae474 2020-10-04)

info: checking for self-updates

$ rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-05
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date

$ WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release
   Compiling ring v0.16.15
   Compiling snow v0.7.1
   Compiling zstd-sys v1.4.17+zstd.1.4.5
   Compiling libloading v0.5.2
   Compiling sp-arithmetic v2.0.0
   Compiling fork-tree v2.0.0
   Compiling finality-grandpa v0.12.3
error[E0282]: type annotations needed
    --> /Users/treasersmac/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1595 | / implement_fixed!(
1596 | |     FixedI64,
1597 | |     test_fixed_i64,
1598 | |     i64,
...    |
1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
1602 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/treasersmac/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1604 | / implement_fixed!(
1605 | |     FixedI128,
1606 | |     test_fixed_i128,
1607 | |     i128,
...    |
1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
1612 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /Users/treasersmac/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1614 | / implement_fixed!(
1615 | |     FixedU128,
1616 | |     test_fixed_u128,
1617 | |     u128,
...    |
1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
1622 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sp-arithmetic`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

my environment: 
```
$ rustup toolchain list
stable-x86_64-apple-darwin (default)
nightly-2020-10-05-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.48.0-x86_64-apple-darwin
```

**Comment by tkimmm** [comment]
I ran into the same error, I managed to resolve it by changing my active toolchain from 1.49 to 1.45.1 then running `make build` again

https://github.com/paritytech/substrate/issues/7150#issuecomment-695344950

**Comment by tkimmm** [comment]
Ok so a bit of experimentation this morning. 

Mac OSX

1) make init 

2) run `echo "nightly-2020-10-05-x86_64-apple-darwin" >> rust-toolchain`

3) make build

**Comment by ashwinYardi** [comment]
Is this an issue with the latest nightly builds? @tkimmm

**Comment by tkimmm** [comment]
Yes, I think there was a breaking change upstream, moreover the init scripts seem to default to the linux toolchain for Rust so you just need to switch it over.

**Comment by treasersimplifies** [comment]
That's solve my problem, thank you very very much!

**Comment by sebastinez** [comment]
Just in case and for eventual future reference. If you get the same error, check that your `rustc --version` is 1.48.0 if you find yourself on 1.49.0 you get the same error message.

**Comment by j-elmer123** [comment]
try with this one `rustup default nightly-2020-10-05` found it on Element chat group.

**Comment by bjwswang** [comment]
@j-elmer123  your solution works in my environment `ubuntu18.04`. Thanks a lot!

**Comment by pkrasam** [comment]
Had a similar issue here and your suggestion @j-elmer123 worked - thank you

**Comment by kirankumarhm** [comment]
I ran into the same error, initially I tried with default nightly-2020-10-05, then nightly-2020-10-01 and nightly-2020-10-06... but nothing is working.

Steps followed to downgrade the nightly are : 
- rustup uninstall nightly
- rustup install nightly-<yyyy-MM-dd>
- rustup target add wasm32-unknown-unknown --toolchain nightly-<yyyy-MM-dd>
- WASM_BUILD_TOOLCHAIN=nightly-<yyyy-MM-dd> cargo build --release

but every time i get the same error. 
![Substrate Build Issue](https://user-images.githubusercontent.com/6735087/104418574-2130ba00-559d-11eb-9ba5-df79f603d9be.png)

**Comment by j-elmer123** [comment]
> I ran into the same error, initially I tried with default nightly-2020-10-05, then nightly-2020-10-01 and nightly-2020-10-06... but nothing is working.
> 
> Steps followed to downgrade the nightly are :
> 
> * rustup uninstall nightly
> * rustup install nightly-<"yyyy-MM-dd">
> * rustup target add wasm32-unknown-unknown --toolchain nightly-<"yyyy-MM-dd">
> * WASM_BUILD_TOOLCHAIN=nightly-<"yyyy-MM-dd"> cargo build --release
> 
> I have tried on both Windows and Ubuntu 18.04 environment. But every time I get the same error.
> 
> ![Substrate Build Issue](https://user-images.githubusercontent.com/6735087/104418574-2130ba00-559d-11eb-9ba5-df79f603d9be.png)

Have you really done `rustup default nightly-2020-10-05`? or would you like to have a google meet with me so I can try to look at that.

**Comment by kirankumarhm** [comment]
Yes I did rustup default nightly-2020-10-05 which is default one. It would be great help if we can have google meet

**Comment by kirankumarhm** [comment]
> > I ran into the same error, initially I tried with default nightly-2020-10-05, then nightly-2020-10-01 and nightly-2020-10-06... but nothing is working.
> > Steps followed to downgrade the nightly are :
> > 
> > * rustup uninstall nightly
> > * rustup install nightly-<"yyyy-MM-dd">
> > * rustup target add wasm32-unknown-unknown --toolchain nightly-<"yyyy-MM-dd">
> > * WASM_BUILD_TOOLCHAIN=nightly-<"yyyy-MM-dd"> cargo build --release
> > 
> > I have tried on both Windows and Ubuntu 18.04 environment. But every time I get the same error.
> > ![Substrate Build Issue](https://user-images.githubusercontent.com/6735087/104418574-2130ba00-559d-11eb-9ba5-df79f603d9be.png)
> 
> Have you really done `rustup default nightly-2020-10-05`? or would you like to have a google meet with me so I can try to look at that.

Yes I did rustup default nightly-2020-10-05 which is default one. It would be great help if we can have google meet

**Comment by j-elmer123** [comment]
@kirankumarhm you can also join the Element room of substrate technical (public) and ask there or add me (`@john_elmer:matrix.org`) on Element so we can arrange meeting time to discuss this problem

**Comment by kirankumarhm** [comment]
> > > I ran into the same error, initially I tried with default nightly-2020-10-05, then nightly-2020-10-01 and nightly-2020-10-06... but nothing is working.
> > > Steps followed to downgrade the nightly are :
> > > 
> > > * rustup uninstall nightly
> > > * rustup install nightly-<"yyyy-MM-dd">
> > > * rustup target add wasm32-unknown-unknown --toolchain nightly-<"yyyy-MM-dd">
> > > * WASM_BUILD_TOOLCHAIN=nightly-<"yyyy-MM-dd"> cargo build --release
> > > 
> > > I have tried on both Windows and Ubuntu 18.04 environment. But every time I get the same error.
> > > ![Substrate Build Issue](https://user-images.githubusercontent.com/6735087/104418574-2130ba00-559d-11eb-9ba5-df79f603d9be.png)
> > 
> > 
> > Have you really done `rustup default nightly-2020-10-05`? or would you like to have a google meet with me so I can try to look at that.
> 
> Yes I did rustup default nightly-2020-10-05 which is default one. It would be great help if we can have google meet

**Comment by kirankumarhm** [comment]
> @kirankumarhm you can also join the Element room of substrate technical (public) and ask there or add me (`@john_elmer:matrix.org`) on Element so we can arrange meeting time to discuss this problem

I have added substraTEE on Element, is that correct one?

**Comment by j-elmer123** [comment]
> I have added substraTEE on Element, is that correct one?
nope, `#substrate-technical:matrix.org` add that one

**Comment by kirankumarhm** [comment]
> #substrate-technical:matrix.org

Yes, I joined with name elogic

**Comment by j-elmer123** [comment]
> Yes, I joined with name elogic

`Substrate Technical (Public)`

**Comment by kirankumarhm** [comment]
> > Yes, I joined with name elogic
> 
> `Substrate Technical (Public)`

Yes, that's the room I joined and I pinged you

**Comment by kirankumarhm** [comment]
Hi, It worked, I am able to build successfully. Commands are below:

git reset --hard
git status
rustup default nightly-2020-10-05
make init
make build

**Comment by NukeManDan** [comment]
@treasersimplifies and all - https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v2.0.1 should fix this. If you are willing, please try:

```bash
rustup default stable
# cd  into the substrate-node-template dir
git checkout master
git pull
cargo clean # might not be needed...
make init
make build
# get a coffee.... ;) 
```

and see if your build issues on top of a clean clone of the template help. Let us know if not!

**Comment by ftsguy** [comment]
@NukeManDan its still failing for me using the master branch which appears was merged with 2.0.1. See below error 

 Compiling fork-tree v2.0.0
error[E0282]: type annotations needed
    --> /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1595 | / implement_fixed!(
1596 | |     FixedI64,
1597 | |     test_fixed_i64,
1598 | |     i64,
...    |
1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
1602 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1604 | / implement_fixed!(
1605 | |     FixedI128,
1606 | |     test_fixed_i128,
1607 | |     i128,
...    |
1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
1612 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1614 | / implement_fixed!(
1615 | |     FixedU128,
1616 | |     test_fixed_u128,
1617 | |     u128,
...    |
1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
1622 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sp-arithmetic`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:19: build] Error 101

**Comment by ftsguy** [comment]
@NukeManDan disregard above i was following the instructions on this page https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup. and i cloned the 2.0.0 version that was listed in the directions. i change the git clone command to 2.0.1 and it built correctly. Not sure who can update those instructions but it needs to be updated. Thanks for the fix !

**Comment by NukeManDan** [comment]
So glad that fixed it! 2.0.1 wiki and docsl references will be updated very soon.

**Comment by lucgerrits** [comment]
I just had the same problem with 2.0.1 and rustc 2021-01-25. After switching to rustc 2020-10-04 it worked fine.
Laptop:
- ubuntu 20.04
- intel i7

**Comment by bhavesh20-mb** [comment]
> > I ran into the same error, initially I tried with default nightly-2020-10-05, then nightly-2020-10-01 and nightly-2020-10-06... but nothing is working.
> > Steps followed to downgrade the nightly are :
> > 
> > * rustup uninstall nightly
> > * rustup install nightly-<"yyyy-MM-dd">
> > * rustup target add wasm32-unknown-unknown --toolchain nightly-<"yyyy-MM-dd">
> > * WASM_BUILD_TOOLCHAIN=nightly-<"yyyy-MM-dd"> cargo build --release
> > 
> > I have tried on both Windows and Ubuntu 18.04 environment. But every time I get the same error.
> > ![Substrate Build Issue](https://user-images.githubusercontent.com/6735087/104418574-2130ba00-559d-11eb-9ba5-df79f603d9be.png)
> 
> Have you really done `rustup default nightly-2020-10-05`? or would you like to have a google meet with me so I can try to look at that.

yes i also have same problem ,can some body help me,

**Comment by treasersimplifies** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,

**Comment by jacobnash** [comment]
> [bhavesh20-mb](/bhavesh20-mb)

Could you confirm what tag you checked out? If you follow some of the online guides they have you checkout v2.0.0 once you move to v2.0.1 that got rid of the error for me. 

git clone -b v2.0.1 --depth 1 https://github.com/substrate-developer-hub/substrate-front-end-template
