### ISSUE TITLE
Improve Substrate tutorial "Permissioned Network"

### ISSUE THREAD

**Issue by VITALcleantech** [substrate-developer-hub/substrate-node-template#266]
Proposed updates to Permissioned Network tutorial

*In order of the Tutorial
**MacOS, Intel, terminal.app (textedit.app to edit files)

1. Add the node Authorization pallet
1A. In file: **runtime/Cargo.toml**
 
Tutorial says to:
Add in the upper dependencies area:
[dependencies]
pallet-node-authorization = { default-features = false, version = '3.0.0' }

**Change this edit to mimic the Nick’s Pallet Tutorial 

[dependencies.pallet-node-authorization]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-10'
version = '4.0.0-dev'

2. Add genesis storage for our pallet
2B. in **node/src/chain_spec.rs**
use sp_core::OpaquePeerId; // A struct wraps Vec<u8>, represents as our `PeerId`.
use node_template_runtime::NodeAuthorizationConfig; // The genesis config that serves for our pallet.

in the fn testnet_genesis section:
node_authorization: NodeAuthorizationConfig {
            nodes: vec![
                (
                    OpaquePeerId(bs58::decode("12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2").into_vec().unwrap()),
                    endowed_accounts[0].clone()
                ),
                (
                    OpaquePeerId(bs58::decode("12D3KooWQYV9dGMFoRzNStwpXztXaBUjtPqi6aU76ZgUriHhKust").into_vec().unwrap()),
                    endowed_accounts[1].clone()
                ),
            ],
        }),

**Delete ")" on the bottom line "}),".  This is a "mismatched closing delimiter".

**Comment by sacha-l** [comment]
@VITALcleantech - thanks for your note here. I believe the issues you're raising have been addressed and fixed in [this PR](https://github.com/substrate-developer-hub/substrate-docs/pull/607) in our docs repository.

**Comment by VITALcleantech** [comment]
@sacha-l @NukeManDan 
Thank you for correcting #1 above, "dependencies".

#2 is still an issue though.  I noticed the extra ")" on the last line of code to be added to file: node/src/chain_spec.rs.  If I delete this ")", the cargo build -- release command compiles correctly.

**Comment by sacha-l** [comment]
Thanks! Fixed now.
